### ISSUE TITLE
chirpunk improvements: tracking issue

### ISSUE THREAD

**Issue by nicopap** [nicopap/cuicui_layout#88]
- [ ] use `Distribution::Overlap` for the main menu background & menu swatch (instead of re-parenting
- [ ] Removing the nesting on spawned scenes, as we now spawn directly the root on the chirp seed entity
- [ ] Move the BACK button to a different menu than the tab bar, so that pressing LT and RT do not focus it
- [ ] Show gamepad controls when gamepad is used.
- [ ] Highlight the settings button as well when the row gains focus
- [ ] Actually hook the settings button to some logic so as they do something
- [ ] Implement hidden debug layout toggle
